version: "3"

services:
  postgres:
    restart: always
    image: postgres:latest
    networks:
      - main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: postgres.env

  library:
    restart: always
    build: ../
    image: library
    ports:
      - "8000:8000"
    networks:
      - main
    volumes:
      - ../:/usr/src/app/
    env_file: .env
    environment:
      - DEBUG=true
    depends_on:
      - "postgres"
    command: ["dev", "${POPUlATE_ON_START}"]

networks:
  main:

volumes:
  pgdata:

